#!/bin/sh

argument=$1

if [ "$argument" = "init" ]; then
    echo "=== Running wrapped 'meltano init' ==="
    rm meltano.yml
    meltano init new_project
    rm new_project/README.md
    mv new_project/* .
    rm -r new_project/
    mkdir data
    cp codespaces_tutorial/customers.csv data/customers.csv
    meltano environment add codespace
    meltano config meltano set default_environment codespace
    echo "=== Now head to the README.md and continue with step 2!"
elif [ "$argument" = "clear" ]; then
    echo "=== Running clear state ==="
    meltano state clear dev:tap-csv-to-target-duckdb
    rm output/my.duckdb
elif [ "$argument" = "select_db" ]; then
    echo "=== Running select DB ==="
    python codespaces_tutorial/select_duckdb.py
else 
    echo "provide one of init|select_db"
fi
