version: 1
default_environment: codespace
project_id: a8bdf4f3-f789-4ffc-9adc-0e0414df9059
environments:
- name: dev
- name: staging
- name: prod
- name: codespace
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: raw_customers
        path: data/customers.csv
        keys: [id]
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: output/my.duckdb
      default_target_schema: raw
  mappers:
  - name: transform-field
    variant: transferwise
    pip_url: pipelinewise-transform-field
    mappings:
    - name: hide-ips
      config:
        transformations:
        - field_id: ip_address
          tap_stream_name: raw_customers
          type: HASH
jobs:
- name: el_without_ips
  tasks:
  - tap-csv hide-ips target-duckdb
venv:
  backend: uv
