name: Pipeline for testing codespaces demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '30 08 * * *'

jobs:
  test_init:
    name: "test_init"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run test script
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        env:
          MELTANO_SEND_ANONYMOUS_USAGE_STATS: false
        with:
          push: never
          runCmd: ./meltano_tut init
          env: MELTANO_SEND_ANONYMOUS_USAGE_STATS
  test_add_plugins:
    name: "test_add_plugins"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run test script
        env:
          MELTANO_SEND_ANONYMOUS_USAGE_STATS: false
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          push: never
          runCmd: ./meltano_tut init ; ./codespaces_tutorial/quick_add_plugins
          env: MELTANO_SEND_ANONYMOUS_USAGE_STATS

  test_run_everything:
    name: "test_run_everything"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run test script
        env:
          MELTANO_SEND_ANONYMOUS_USAGE_STATS: false
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          push: never
          runCmd: ./codespaces_tutorial/walkthrough
          env: MELTANO_SEND_ANONYMOUS_USAGE_STATS
